### ISSUE TITLE
Should I deactivate Pylance while using this extension?

### ISSUE THREAD

**Issue by ddahan** [charliermarsh/ruff-vscode#133]
I was wondering if there is any interest keeping Pylance along with Ruff in VS Code linting.

I did not find a case inwhich Pylance spots an error while Ruff doesn't. For example:

<img width="460" alt="image" src="https://user-images.githubusercontent.com/1933516/219699474-23d67ca6-117d-4e19-b9ff-085a78fe1b54.png">

Is there anything I miss if I remove Pylance?

Thanks for the amazing work!!

**Comment by ddahan** [comment]
Auto-reply: deactivating Pylance broke import suggestions and auto imports, so I let it in parralel with Ruff.

Is there any way to keep Pylance, but not for linting? To avoid duplicate error messages.

**Comment by charliermarsh** [comment]
Yeah I recommend keeping Pylance enabled, since Ruff isn't a _general_ LSP -- so it doesn't do jump-to-completion, or import suggestions, etc.

I'm not certain if there's a good way to disable _just_ Pylance's diagnostics. I'd love to know if you find a good way to do that.

**Comment by ejgal** [comment]
Adding this to settings.json seems to disable only the linting part of pylance
`"python.analysis.ignore": [
        "*"
    ]
`

https://stackoverflow.com/a/75071893

**Comment by charliermarsh** [comment]
Oh interesting, thanks!

**Comment by Veritogen** [comment]
@ejgal thanks for the suggestion. Unfortunately its not working for me at the moment. I don't know if this is due to recent changes or if its something specific to my configuration. Right now I either receive duplicate hints by ruff and pylance and can use the quickfix for importing or I only have the hints by ruff and no quick fixes for importing. 

What was actually working for me is the following (found here: https://github.com/microsoft/pylance-release/discussions/4249#discussioncomment-5642352) 
```
  "python.analysis.diagnosticSeverityOverrides": {
    "strictListInference": "none",
    "strictDictionaryInference": "none",
    "strictSetInference": "none",
    "analyzeUnannotatedFunctions": "none",
    "strictParameterNoneValue": "none",
    "enableTypeIgnoreComments": "none",
    "reportMissingModuleSource": "none",
    "reportMissingImports": "none",
   // reportUndefinedVariable": "none"
  },
  ```
Either uncommenting `reportUndefinedVariable": "none"` or removing it does the trick. In this case I still have duplicate messages for undefined variables, but I can at least use Pylances/VSCodes quick fixes.

**Comment by IzaakC** [comment]
When using a pyproject file:

```toml
[tool.pyright]
typeCheckingMode = "off"
ignore = ["*"]
```
