### ISSUE TITLE
Use existing ruff in active python environment

### ISSUE THREAD

**Issue by buhrmann** [charliermarsh/ruff-vscode#141]
Hi, unless I'm missing something, it's not currently possible to configure the Ruff extension to use an already existing Ruff install in the _currently active_ Python environment. There are options to manually set a fixed path to the interpreter and Ruff binary, but that's no use if you habitually switch between different python environments in VS Code.

The problem is that this leads to possibly incongruent linting via the extension and any configured pre-commit linting with Ruff. If the extension updates and introduces new rules, e.g., but the pre-commit Ruff has a fixed prior version, the result of the two may differ.

Not sure if it's possible to add the option to use the same Ruff already installed in the environment, or used by pre-commit, or if there is an alternative way to ensure consistency?

**Comment by charliermarsh** [comment]
If you use `importStrategy: fromEnvironment`, it should behave this way -- it'll pick up the Ruff from the current workspace environment, using the same logic as all other VS Code Python extensions (it's picked up from Microsoft's template -- nothing specific to Ruff).

**Comment by buhrmann** [comment]
Uff, totally missed that setting, and there are only nine hahaha. Thanks!

**Comment by sjdemartini** [comment]
@charliermarsh Instead of requiring a setting to be changed, is it possible to have the Ruff extension prefer the workspace environment by default if it can find that `ruff` is installed there, and only fall back to the bundled version of ruff if not? This is for instance how the [Pylint](https://github.com/microsoft/vscode-pylint#pylint-extension-for-visual-studio-code) and [Flake8](https://github.com/microsoft/vscode-flake8#flake8-extension-for-visual-studio-code) extensions from Microsoft work—e.g.
> The bundled `pylint` is only used if there is no installed version of `pylint` found in the selected `python` environment.

We have a shared repo for our workplace, and we want to ensure that everyone using it with VSCode has a consistent dev experience out of the box. So we'd like `ruff` to behave the same for everyone based on the version we have pinned in our environment. As a workaround, I tried putting `"ruff.importStrategy": "fromEnvironment",` in our `.vscode/settings.json` file, but it seems that setting doesn't take effect within workspaces and so must be applied manually by each user to their own user or other settings if they want to use the locally-installed environment version of ruff:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/1647130/222213906-a3b5f748-217c-4c43-b9d9-8bfa966613f6.png">

Thanks for considering!

**Comment by charliermarsh** [comment]
Yeah I think it makes sense to change the default.

**Comment by sjdemartini** [comment]
Okay, nice, it looks like the import strategy default was actually already being set as `fromEnvironment` based on:

https://github.com/charliermarsh/ruff-vscode/blob/f57ae4f1cad2e7ea3a9caa307898fdfacbd180f1/src/common/settings.ts#L51


It's just that the docs didn't reflect that. I made a PR to update them: https://github.com/charliermarsh/ruff-vscode/pull/144

**Comment by buhrmann** [comment]
Hm, I'm still having problems. Even if I use the `fromEnvironment` options it doesn't always seem to use the correct version of Ruff: 

![image](https://user-images.githubusercontent.com/190342/224362841-2b8fe0a6-40fb-4323-b17d-ac90e80ce05e.png)

As you can see in the image, Ruff says "Using environment executable: /Users/thomas/mambaforge/bin/ruff", which is the base environment, while VS Code's active environment is not the base environment, but one named "grapy" (see lower right corner of the screenshot).

I'm pretty sure at some point I saw Ruff pointing at the correct executable in the active environment. Not sure what changed.

**Comment by charliermarsh** [comment]
Yeah I think it's wrong. It should be using current environment, _then_ global environment, but it's inverted AFAICT.

**Comment by buhrmann** [comment]
Ok. No problem, I've got a workaround for now. Just thought it better to report. Thanks for looking into it!
